export const GET_PRODUCTS="GET_PRODUCTS"
export const GET_PRODUCT="GET_PRODUCT"
export const PRODUCT_ERROR="PRODUCT_ERROR"

export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL="USER_LOGIN_FAIL"

export const ORDER_LIST_REQUEST="ORDER_LIST_REQUEST"
export const ORDER_LIST_SUCCESS="ORDER_LIST_SUCCESS"
export const ORDER_LIST_FAIL="ORDER_LIST_FAIL"
export const ORDER_MARK_DELIVER_REQUEST="ORDER_MARK_DELIVER_REQUEST"
export const ORDER_MARK_DELIVER_SUCCESS="ORDER_MARK_DELIVER_SUCCESS"
export const ORDER_MARK_DELIVER_FAIL="ORDER_MARK_DELIVER_FAIL"



export const USER_REGISTER_REQUEST="USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS="USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL="USER_REGISTER_FAIL"
export const USER_LOGOUT="USER_LOGOUT"
export const CART_ADD_ITEM="CART_ADD_ITEM"
export const CART_REMOVE_ITEM="CART_REMOVE_ITEM"
export const CART_SAVE_SHIPPING="CART_SAVE_SHIPPING"
export const CART_SAVE_PaymentMethod="CART_SAVE_PaymentMethod"

export const ORDER_CREATE_REQUEST="ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS="ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL="ORDER_CREATE_FAIL"
export const ORDER_CREATE_RESET="ORDER_CREATE_RESET"
export const ORDER_PAY_RESET="ORDER_PAY_RESET"
export const ORDER_PAY_SUCCESS="ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL="ORDER_PAY_FAIL"
export const ORDER_PAY_REQUEST="ORDER_PAY_REQUEST"
export const PRODUCT_CREATE_RESET="PRODUCT_CREATE_RESET"

export const ORDER_DETAILS_REQUEST="ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS="ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL="ORDER_DETAILS_FAIL"

export const PRODUCT_CREATE_REQUEST="PRODUCT_CREATE_REQUEST"
export const PRODUCT_CREATE_SUCCESS="PRODUCT_CREATE_SUCCESS"
export const PRODUCT_CREATE_FAIL="PRODUCT_CREATE_FAIL"

export const PRODUCT_UPDATE_REQUEST="PRODUCT_UPDATE_REQUEST"
export const PRODUCT_UPDATE_SUCCESS="PRODUCT_UPDATE_SUCCESS"
export const PRODUCT_UPDATE_FAIL="PRODUCT_UPDATE_FAIL"

export const USER_LIST_REQUEST="USER_LIST_REQUEST"
export const USER_LIST_SUCCESS="USER_LIST_SUCCESS"
export const USER_LIST_FAIL="USER_LIST_FAIL"






